### 1. Calculate Area of a Circle


In [3]:
PI = 3.14
r = float(input("Enter the radius :"))
area = PI * r * r
print(f"Area of a circle = {area}")

Enter the radius :2
Area of a circle = 12.56


### 2. Say Hello to user, Expected, ‘Hello name’

In [5]:
name=input("Enter your name :")
print(f"Hello {name}")

Enter your name :Shakiba
Hello Shakiba


### 3. Calculate Volume of Sphere

In [6]:
PI = 3.14
r = float(input("Enter the radius :"))
volume = 4/3 *PI * r * r* r
print(f"Volume of sphere = {volume}")

Enter the radius :6
Volume of sphere = 904.3199999999998


### 4. Copy String in n times

In [13]:
your_string=input("Enter your string :")
n=int(input(" "))
print(your_string *n)



Enter your string :shakiba
 2
shakibashakiba


In [24]:
def repeat(a, b):
    repeated_string = a * b
    return repeated_string

r = repeat("Hi", 10)
print(r)

HiHiHiHiHiHiHiHiHiHi


### 5. Calculate Area of a Triangle

In [15]:
a = float(input('Enter first side: '))  
b = float(input('Enter second side: '))  
c = float(input('Enter third side: '))  
    
s = (a + b + c) / 2   
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5  
print(f'The area of the triangle is {area}') 

Enter first side: 1
Enter second side: 3
Enter third side: 6
The area of the triangle is (3.8726732145403874e-16+6.324555320336759j)


### 6. Calculate Interest


In [29]:
def Interest(p,r,t):
    print('The principal is', p)
    print('The time period is', t)
    print('The rate of interest is',r)
    Calculate_Interest = (p*r*t)/100
    print('The Interest is', Calculate_Interest)
    return Calculate_Interest

I = Interest(100,2,8)


The principal is 100
The time period is 8
The rate of interest is 2
The Interest is 16.0


### 7. calculate Euclidean Distance

In [38]:
def distance(A, B):
    D=(((A[0]-B[0])**2)+((A[1]-B[1])**2)+((A[2]-B[2])**2))**0.5
    return D

A=(2,3,4)
B=(1,2,0)
ED=distance(A, B)
print("{:.2f}".format(ED))
    
        
        

4.24


### 8. Feet to centimeter Converter

In [42]:
def convert(feet):
    c=30.48 * feet
    return c
D= convert(3)
print(f"{D} centimeter")

91.44 centimeter


### 9. BMI Calculator

In [43]:
height = float(input("Enter your height in cm: "))
weight = float(input("Enter your weight in kg: "))
BMI = weight / (height/100)**2
print(f"You BMI is {BMI}")

Enter your height in cm: 160
Enter your weight in kg: 67
You BMI is 26.171874999999996


### 10. Binary to Decimal


In [46]:
number= input('Enter a Binary number:')
dec_number= int(number, 2)
print('The decimal conversion is:', dec_number)
print(type(dec_number))

Enter a Binary number:1011
The decimal conversion is: 11
<class 'int'>


### 11. receive two integral numbers in string form and compute their sum and then print it in console.

In [66]:
def calculateSum (a,b):
    s = int(a) + int(b)
    return s 

num1 = "10"
num2 = "20"
sum = calculateSum (num1, num2)  
print ("Sum = ", sum)


Sum =  30


### 12. bitwise operators for any two variable all the bitwise operator that are there

In [1]:
x=10 # 0000 1010 
y=4 # 0000 0100
print(x&y)
print(x|y)
print(~x)
print(x^y)

0
14
-11
14


### 13. Shift operator

In [2]:
print(x>>2)
print(x<<2)

2
40


### 14.str1=" this is a sample daTaa to test for the task" Check if ‘is’ present in str1

In [73]:
str1=" this is a sample daTaa to test for the task"
if "present" not in str1:
    print(str1.upper())
    
    

 THIS IS A SAMPLE DATAA TO TEST FOR THE TASK


In [74]:
print(str1.title())

 This Is A Sample Dataa To Test For The Task


In [80]:
L=str1.split()
L[4]="Dataa"
print(L)

['this', 'is', 'a', 'sample', 'Dataa', 'to', 'test', 'for', 'the', 'task']


In [82]:
S = ' '.join( L)
print(S)

this is a sample Dataa to test for the task


In [84]:
x = S.replace("Dataa", "Data")
print(x)

this is a sample Data to test for the task


In [4]:
str2="this is another sample string"
L2=str2.split()

In [5]:
print(L2[3])

sample


In [ ]:
T= 21-oct-2020
from datetime import datetime
print(datetime.now().day)

### 21.Display date, month and year form 21-oct-2020

In [27]:
from datetime import datetime
datestring = "21-oct-2020"
dt = datetime.strptime(datestring,"%d-%b-%Y")
print (dt.day,dt.month,dt.year)


21 10 2020


### 22. arr = “10,20,30,40,50,60,70”, get “50,60”

In [12]:
arr="10,20,30,40,50,60,70"
A=arr.split(",")
print(f"{A[4]},{A[5]}")

50,60


### 23.using negative index get "50 ,60"

In [13]:
arr="10,20,30,40,50,60,70"
A=arr.split(",")
print(f"{A[-3]},{A[-2]}")

50,60


### 24. From credit_str get ‘8888’ credit_str = "xxxx----xxxx-8888------xxxx"

In [17]:
import re
credit_str = "xxxx----xxxx-8888------xxxx"
print(credit_str[13:17])

8888


### 25. From credit_str get ‘0’ credit_str = "1234-5678-9878-0434"

In [19]:
credit_str = "1234-5678-9878-0434"
print(credit_str[15])

0


### 26. convert a integer into a string and print it in console.

In [23]:
num=3
print(type(num))
s=str(num)
print(type(s))

<class 'int'>
<class 'str'>


### 27. take two strings as input and concatenate them and then print it

In [24]:
A=input("")
B=input("")
print(A+B)

hi
shakiba
hishakiba


### 28. convert the given string into list given_string = " Apples is differnt from Apple Inc"

In [26]:
given_string = " Apples is differnt from Apple Inc"
L=given_string.split()
print(L)

['Apples', 'is', 'differnt', 'from', 'Apple', 'Inc']


### 29. print type of a and get the 1 element a = {(1,2):1,(2,3):2}

In [30]:
a = {(1,2):1,(2,3):2}
print(type(a))
print(a[(1,2)])

<class 'dict'>
1


### 30. write a program to get list as 4,3,2 from the list below a=1,2,3,4,5

In [41]:
a=[1,2,3,4,5]
b=a[-1::-1]
print(b[1:4])

[4, 3, 2]


### 31.write a program to get odd number only using a slicing a=1,2,3,4,5,6,7,8,9

In [47]:
a=1,2,3,4,5,6,7,8,9
print(a[::2])

(1, 3, 5, 7, 9)


### 32. create a tuple with (1,2) 5 times

In [5]:
T=((1,2),)*5
print(T)

((1, 2), (1, 2), (1, 2), (1, 2), (1, 2))


### 33. from given list create separate lists of strings and numbers.use list comprehension gadgets = "Mobile", "Laptop", 100, "Camera", 310.28, "Speakers", 27.00, "Television", 1000, "Laptop Case", "Camera Lens"

In [15]:
gadgets = ["Mobile", "Laptop", 100, "Camera", 310.28, "Speakers", 27.00, "Television", 1000, "Laptop Case", "Camera Lens"]
A=[print(i)       for i in gadgets
  if type(i)==str]

Mobile
Laptop
Camera
Speakers
Television
Laptop Case
Camera Lens


In [18]:
gadgets = ["Mobile", "Laptop", 100, "Camera", 310.28, "Speakers", 27.00, "Television", 1000, "Laptop Case", "Camera Lens"]
B=[print(i)       for i in gadgets
  if type(i)!=str]

100
310.28
27.0
1000


### 34. An array is given from the array find the sum of diagonal using list comprehension a_2d=[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
a_2d=[1, 2, 3, 4, 5, 6, 7, 8, 9]
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
l = len(grid[0])
print(sum([grid[i][i] for i in range(l)])  )            
print(sum([grid[l-1-i][i] for i in range(l-1,-1,-1)]))

15
15


### 35. convert number into tuple of words using comprehension num=8976543201

In [59]:
num=8976543201
num1=str(num)
L=[i for i in num1]
print(tuple(L))



('8', '9', '7', '6', '5', '4', '3', '2', '0', '1')


### 36. print the numbers which are divisible by 2 but are not a multiple of 5 numbers = range(1, 10)

In [65]:
numbers = range(1, 10)
print(numbers)
L=[i   for i in numbers
if i%2==0 and i%5!=0]
print(L)

range(1, 10)
[2, 4, 6, 8]


### 37. print the sum of tuple : use comprehension init_tuple = [(0, 1), (1, 2), (2, 3)]

In [68]:
init_tuple = [(0, 1), (1, 2), (2, 3)]
[i[0]+i[1]      for i in init_tuple ]

[1, 3, 5]

### 38. delete the last coumn from the given 4*4 matrix arr = [[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [75]:
arr = [[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
subarray = np.delete(arr,-1, axis=1)
subarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

### 39. get the list of value of dict in sorted way dict = {'c': 97, 'a': 96, 'b': 98}

In [79]:
dict = {'c': 97, 'a': 96, 'b': 98}
dict.values()

dict_values([97, 96, 98])

### 40. Creating a Dictionary with Integer Keys and print it

In [87]:
D={}
for (k,v) in zip(range(1, 4), range(1, 4)):
    D[k] = v

print(D)

{1: 1, 2: 2, 3: 3}


In [83]:
dict.fromkeys(range(1, 4))
{1: None, 2: None, 3: None}

{1: None, 2: None, 3: None}

### 41. Creating a Dictionary with Mixed keys

In [ ]:
dict_sample = {'brand': 'Tesla', 1: [4, 0]}

### 42. Creating an empty Dictionary

In [88]:
D={}
print(D)

{}


### 43. Creating a Dictionary with dict() method

In [3]:
result= dict([(4,2),(3,2)])  
print(result)


{4: 2, 3: 2}


### 44. Creating a Dictionary with each item as a Pair

In [ ]:
result= dict([(4,2),(3,2)])  
print(result)

### 45. Creating a Nested Dictionary as shown in the below image {1: 'python', 2: 'For', 3: {'A': 'Welcome', 'B': 'To', 'C': 'Python', 'D': 'class'}}

In [2]:
a=(1,2,3)
b=("python","For", {'A': 'Welcome', 'B': 'To', 'C': 'Python', 'D': 'class'})
D=list(zip(a,b))
D1=dict(D)
print(D1)

{1: 'python', 2: 'For', 3: {'A': 'Welcome', 'B': 'To', 'C': 'Python', 'D': 'class'}}


### 46. Add a Nested Key value to nested dictionary Dictionary

In [5]:

D1[{1:"shakiba"}]="shakiba"
print(D1)
#That does not work because the keys have to be hashable. As a general rule, only immutable objects (strings, integers, floats, frozensets, tuples of immutables) are hashable (though exceptions are possible). So this does not work:

TypeError: unhashable type: 'dict'

### 47. create a dictionary with id:num and value: square for range (0,6) using dict comprehension

In [6]:
D= dict()
for i in range(6):
    D[i] = i**2
print(D)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


###  48. create a dictionary using dict comprehension to get the odd square only

In [7]:
D= dict()
for i in range(10):
    if i%2!=0:
        D[i] = i**2
print(D)

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}


### 49. from a given dict {1: 'a', 2: 'b', 3: 'c'} change the key into item and viceversa

In [13]:
D={1: 'a', 2: 'b', 3: 'c'}
D1={}
k=D.keys()
v=D.values()
print(k)
print(v)
for i in D:
    D1[D[i]]=i
print(D1)

dict_keys([1, 2, 3])
dict_values(['a', 'b', 'c'])
{'a': 1, 'b': 2, 'c': 3}


### 50. get a hello from the given dict d = {'k1':[{'nest_key':['this is deep','hello']}]}

In [14]:
d = {'k1':[{'nest_key':['this is deep','hello']}]}
print(d["k1"][0]["nest_key"][1])

hello


### 51. Divisibility Check of user given 2 input of numbers

In [17]:
num1 = int(input('Enter num1: '))
num2 = int(input('Enter num2: '))
if(num1%num2 == 0):
    print("Divisible")
else: 
    print("Not Divisible")
    

Enter num1: 3
Enter num2: 4
Not Divisible


### 52. Check if number is even or odd

In [19]:
num=int(input(" "))
if num%2==0:
    print("even")
else:
    print("odd")

 3
odd


### 53. Check whether Entered character is Vowel or not

In [24]:
Vowels=["a","e","o","u","i","A","E","O","U","I"]
character=input("Enter your character: ")
if character in Vowels:
    print("Vowel")
else:
    print(" Not Vowel")

Enter your character: r
 Not Vowel


### 54. calculate Sum of n positive Integer example: Sum of n positive Integer till 2 is 3

In [28]:
s=0
n= int(input(" "))
for i in range(0,n+1):
    s=s+i
print(s)

 5
15


### 55. calculate the Digit Sum of a number (eg: 123 print 1+2+3=6)

In [35]:
n= int(input(" "))
num1=str(n)
L=[int(i) for i in num1]
s=0
for j in L:
    s=s+j
print(s)
    

 12345
15


### 56. Count Numbers, Alphabets, and Special Character from user input string

In [37]:
char=input(" ")
L=[i for i in char]
print(len(L))
    

 123shakiba&
11


### 57. constuct the given pattern

In [9]:
for i in range(0,9):
    if i<=4:
        print((i+1)* "*" )
    else:
        print((9-i)*"*")
    

*
**
***
****
*****
****
***
**
*


### 58. Count number of characters in a string eg : {'h': 1, 'e': 1, 'l': 2, 'o': 1}

In [11]:
from collections import Counter
print(Counter('Hi shakiba'))


Counter({'i': 2, 'a': 2, 'H': 1, ' ': 1, 's': 1, 'h': 1, 'k': 1, 'b': 1})


### 59.write a program to compute 5/0 using try except

In [2]:
try:

    userInput1 = int(input("Enter a number:  "))
    userInput2 = int(input("Enter a number: "))
    answer = userInput1/userInput2
    print ("The answer is ", answer)

except ZeroDivisionError:
    print ("An attempt to divide by 0 was detected.")


Enter a number:  12
Enter a number: 0
An attempt to divide by 0 was detected.


### 60. Handle the exception thrown by the code below by using try and except blocks.


In [40]:
try:
    li=["hello","class"]
    for i in li:
        M=i**2
        print(M)
except TypeError as type_err:
    print(type_err)
    print("typeError")


unsupported operand type(s) for ** or pow(): 'str' and 'int'
typeError


### 61. Write a function that asks for an integer and prints the square of it. Use a while loop with a try,except, else block to account for incorrect inputs.

In [ ]:
example: Input an integer: null
An error occurred! Please try again!
Input an integer: 2
Thank you, you number squared is: 4

In [5]:
def give_number():
    while True:
        try:
            num=int(input(" Enter a number: "))
            A=num ** 2
            print(f"Thank you, you number squared is: {A}" )
        except :
            print("An error occurred! Please try again!")
            continue
        else:
            break
            
a=give_number()

        
    

 Enter a number: 
An error occurred! Please try again!
 Enter a number: 2
Thank you, you number squared is: 4


### 62. Accept the String and print the words composed of digits only

In [9]:
L = []
str_ = "Hi shakiba 222 apple3"
t_str_ = str_.split()
for i in t_str_:
    if any(chr.isalpha() for chr in i) and any(chr.isdigit() for chr in i):
        L.append(i)
L

['apple3']

### 63. find the parity outlier from the given sequence use list comprehension
seq=1,2,3,5,7

In [17]:
seq=1,2,3,5,7
[i    for i in seq 
if i%2==0
]


[2]

### 64. get the complement
where:

```
A ->> T
T -->> A
C --> G
G --> C
```

for the given DNA dna="ATTGC"


In [18]:
dna="ATTGC"
dict1 = {'A':'T','T':'A','C':'G','G':'C'}
"".join((dict1[i]) for i in dna)

'TAACG'

### 65. Write a program that inputs a number from the user and displays the factorial of that number using while loop.

In [12]:
num=int(input("Enter a number:  "))
m=1
i=1
while i<=num:
    m=i*m
    i+=1
print(f"{num}! = {m}")

    
    

Enter a number:  5
5! = 120


### 66. Ask the user for a number,to pick the color from the list print the color.
color= Blue, Green, Orange, Red

In [15]:
color=["Blue", "Green", "Orange","Red"]
dict_={}
color1=tuple(color)
for (k,v) in zip(range(1,5),color1):
    dict_[k] = v
print(dict_)
num=int(input("Enter a number:  "))
print(dict_[num])

{1: 'Blue', 2: 'Green', 3: 'Orange', 4: 'Red'}
Enter a number:  3
Orange


### 67. Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.

In [13]:
digit=int(input("Enter digit:"))
num=input("enter a number:")
 
 
result=0
for i in range(1,digit+1):
  result= result + int(str(num*i))
  print(num*i)
 
print("________________+\n")
print(result)

Enter digit:5
enter a number:2
2
22
222
2222
22222
________________+

24690


## 68. write a program that lets user to input the value seperate by "," and create a list from it using list comprehension

In [1]:
comma_text = input("Enter text with comma: ")
comma_text = comma_text.split(',')
result = []
for i in comma_text:
    result.append(i)
print(result)

Enter text with comma: shakiba,hi,are,you,ok
['shakiba', 'hi', 'are', 'you', 'ok']


### 69. Write a program that calculates and prints the value according to the given formula:


In [ ]:
Q = Square root of (2* C *D)/H
given,
c=50
h=30
D is the variable whose values should be input to your program in a comma-separated sequence.
Example 100,150,180
The output : 18,22,24

In [3]:
import math
numbers_list = input("D: ")
c = 50
h = 30
numbers_list = numbers_list.split(',')
result = []
for D in numbers_list:
    Q = round(math.sqrt(2 * c * int(D) / h))
    result.append(Q)
print(result)

D: 100,150,180
[18, 22, 24]


### 70. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [7]:
str_=input(" Enter your text: ")
L=str_.split(" ")
for i in L:
    counts=L.count(i)
    if counts>=2:
        L.remove(i)
        L.sort()
print((' ').join(L))
        
        



 Enter your text: I have an apple and an green apple
I an and apple green have


### 71. Write a program which accepts a sequence of comma separated 4 digit binary numbers and then check whether they are divisible by 5 or not. print the number.
Example: 0100,0011,1010,1001 Then the output should be: 1010


In [14]:
binary_ = input("Enter numbers:")
splited = binary_.split(',')

number = []
for i in splited:
        number.append(i)
for i in number: 
    if(int(i, 2)%5 == 0):
        print(i)

Enter numbers:0100,0011,1010,1001 
1010


### 72. By using list comprehension, please write a program to print the list after removing the even index numbers
li=range(10)

In [22]:
L=[]
for i in range (10):
    if i%2!=0:
        L.append(i)
print(L)

[1, 3, 5, 7, 9]


### 73. write a function to get the sum of two num(use lambda)

In [24]:
sum_ = lambda x,y: x+y
sum_(4,5)


9

### 74. write a function to print if leap year or not

In [25]:
year = int(input("Enter year:"))
if (year%4 == 0):
    if (year%100 == 0):
        if (year%400 == 0):
            print("leap year")
        else:
            print("leap year")
    else:
        print("leap year")
else:
    print("not a leap year")

Enter year:1985
not a leap year


### 75. write a function to count a bit(number of 1) in number (use lambda)

In [26]:
b = lambda x:x.count('1')
b(input("enter bit strearm: "))

enter bit strearm: 1011


3

### 76. write a program to get the area of a circle from the radius (use lambda)

In [1]:
import math
area = lambda x: math.pi * x * x
area(4)

50.26548245743669

### 77. write a function to get the factorial of given number use recurssion

In [10]:
def factorial(n):
    if type(n) == int and n >=0:
        if n == 0:
            return 1
        else:
            return n * factorial(n-1)
    else:
        raise TypeError("n has to be a positive integer or zero")
        
        
print(factorial(5))


120


In [ ]:
def factorial(n):
    """ calculates the factorial of n, 
        n should be an integer and n <= 0 """
    def inner_factorial(n):
        if n == 0:
            return 1
        else:
            return n * inner_factorial(n-1)
    if type(n) == int and n >=0:
        return inner_factorial(n)
    else:
        raise TypeError("n should be a positve int or 0")

### 78. write a program to remove a duplicate word in a list or user input sentences

In [3]:
str_=input("Enter a sectence:  ")
str1= str_.split()
L=[]
for i in str1:
    count=str1.count(i)
    if count<2:
        L.append(i)
print(L)
        
    

Enter a sectence:  Hi shakiba Hi Sarah
['shakiba', 'Sarah']


### 79. calculate fibonacci

In [4]:
n=int(input(" "))
A=[]
for i in range (0,n):
    if i <=1:
        A.append(i)
    else:
        A.append(A[i-1]+A[i-2])
for j in A:
    print(j)
    
    
    
    
    

 8
0
1
1
2
3
5
8
13


### 80. write a function to get the premutation and combination

In [5]:
from itertools import permutations
from itertools import combinations

perm = permutations([1, 2, 3, 4], 2)
print("permutations:")
for i in list(perm):
    print (i)
    
comb = combinations([1, 2, 3, 4], 2)
print("combinations:")
for i in list(comb):
    print (i)

permutations:
(1, 2)
(1, 3)
(1, 4)
(2, 1)
(2, 3)
(2, 4)
(3, 1)
(3, 2)
(3, 4)
(4, 1)
(4, 2)
(4, 3)
combinations:
(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


### 81. write a function to draw a diamond shape from a user given number: hint: only odd number can draw a diamond shape

In [19]:
n=int(input("Enter odd number: "))
for i in range(0,n):
    if i<(n+1)/2:
        print(((((n-1)//2)-i)*" ")+(2*i+1)*"*")
    else:
        print((((-n+2*i+1)//2)*" ")+(2*n-2*i-1)*"*")
    
        
    

Enter odd number: 11
     *
    ***
   *****
  *******
 *********
***********
 *********
  *******
   *****
    ***
     *


In [49]:
print(((6*" ")+"*"))
print(((5*" ")+"***"))
print(((4*" ")+"*****"))
print(((3*" ")+"*******"))
print(((2*" ")+"*********"))
print(((1*" ")+"***********"))
print(((2*" ")+"*********"))
print(((3*" ")+"*******"))
print(((4*" ")+"*****"))
print(((5*" ")+"***"))
print(((6*" ")+"*"))

      *
     ***
    *****
   *******
  *********
 ***********
  *********
   *******
    *****
     ***
      *


### 82. build a simple calculator which can: add subtract multiply divide

In [16]:
D={"Add":("a+b"),"Subtract":("a-b"),"Multiply":("a*b"),"Divide":("a/b")}
try:
    a=int(input("Number one :"))
    b=int(input("number second: "))
    n = input("Select operation: Add,Subtract,Multiply,Divide")
    print(f"{D[n]} = {eval(D[n])}")
    
except ZeroDivisionError:
    print ("An attempt to divide by 0 was detected.")


Number one :2
number second: 7
Select operation: Add,Subtract,Multiply,DivideDivide
a/b = 0.2857142857142857


### 83. define a function which can print a given string in a circular rotation

In [25]:
str1=input(" ")
str2=[i   for i in str1]
L=[]
for i in range(len(str2)):
    L.append(str2.pop())
print("".join(L))

 shakiba
abikahs


### 84. write a function to calculate the GCD of 2 number

In [23]:
def divider(a):
    L1=[]
    for i in range(1,a+1):
        if a%i==0:
            L1.append(i)
    return L1
    

    
num1=int(input("Enter one number: "))
num2=int(input("Enter second number: "))

L2=[]
for i in divider(num1):
    if i in divider(num2):
        L2.append(i)
print(L2)
        
L2.sort()
print(L2[-1])
        


            
            
            


            

Enter one number: 5
Enter second number: 35
[1, 5]
5


### 85. Write a Python function to check whether a string is pangram or not.

In [22]:
def is_panagram(sentence):
    alphabets='abcdefghijklmnopqrstuvwxyz' 
    b=0
    for letter in alphabets:             
        if letter not in sentence.lower(): 
            return False
        else:
            b=1
    if b!=0:
        return True
        
        

w=is_panagram("The quick brown fox jumps over the lazy dog")
print(w)
    
    

True


### 86. write a function which take a list of number and target where target is number . print the index from the list where the sum of the index value is equal to that of the target

In [22]:
def target_value(target,List):
    A=[]
    for i in range(0,target+1):
        z=target-i
        A.append(z)
        for i in A:
            return [A.index(i),i]
    
    
List = [1,2,3,4,5,6,7,8]
print(target_value(5, List))
    

[0, 5]


### 87. write a function to calculate the LCM of a 2 number lcm of 54 and 42 is 216

In [5]:
def multiples(a,b):
    i=1
    while True:
        c=a*i
        if c%b!=0:
             i+=1
        else:
            break
    return c
    
print(multiples(4,6))
        
        
        

12


### 88. write a function that gives the prime factor only

In [28]:
a=int(input(" "))

def prim(a):
    A=[]
    for j in range(1,a+1):
            if a%j==0:
                A.append(j)
    return A




B=[]
for k in prim(a):
    T=prim(k)
    if len(T)==2:
        B.append(k)
print(B)

     

 12
[2, 3]


### 89. write a function that print the first non repeating letter

In [33]:
def notrepeating(mystring):
    C=[i  for i in mystring]
    A=[]
    for j in C:
        if mystring.count(j)==1:
            A.append(j)
    return A[0]

print(notrepeating("hishakiba"))
   
        

s


### 90. return sum of array excluding the lowest and highest element

In [4]:
import numpy as np
mylist=[100,-2,0,11,4,1]
mylist.sort()
mylist_array=np.array(mylist[1:-1])
print(mylist_array)
sum=0
for i in mylist_array:
    sum+=i
print(sum)


    

[ 0  1  4 11]
16


### 91. define a function take a string value replace any number below 5 with 0 and any number above 5 with 1

In [5]:
def Five_convert(str_):
    li=[]
    for i in str_:
        if int(i)<5:
            li.append(0)
        elif int(i)>=5:
            li.append(1)
    return ' '.join([str(j) for j in li]).replace(' ','')
    
Five_convert("123456789")

'000011111'

### 92. write a function to get a day of week eg: (30,8,2010)=1

### 93. write a function to get all the permutation of the string

In [17]:
def cube (num):
    L=[i**3 for i in range(num)]
    return L
print(cube(5))
    

[0, 1, 8, 27, 64]


In [22]:
def cube (num):
    for i in range(num):
        yield i**3
    return
        
num=5
for i in cube(num):
    print(i)


<generator object cube at 0x7fd608309660>


In [39]:
def permutations(string):
    """
    Create all permutations of a string with non-repeating characters
    """
    permutation_list = []
    if len(string) == 1:
        return [string]
    else:
        for char in string:
            [permutation_list.append(char + a) for a in permutations(string.replace(char, "", 1))]
    return permutation_list

print(permutations("ABC"))

['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']


### 94. write a function to get all the possible subset of a string in a list

In [108]:
def list_string(str):
  L = [x+y for x in str for y in str if len(str) > 1]
  return L

print(list_string("ABCD"))

['AA', 'AB', 'AC', 'AD', 'BA', 'BB', 'BC', 'BD', 'CA', 'CB', 'CC', 'CD', 'DA', 'DB', 'DC', 'DD']


### 95. write a function to get the length of the last word only from a string seperated by space ex:('string of words') == 5 ex:('adasd ')=5

In [109]:
def list_string(str):
    L=str.split(" ")
    return len(L[-1])
print(list_string('string of words'))
        
    

5


### 96. write a program for a tower of hanoi puzzle

### 97. Use a for loop to estimate π from the first 20 terms of the Madhava series:


In [111]:
import math
series = 0
for k in range(20):
    series += math.pow(-3, -k) / (2*k+1)
pi = math.sqrt(12)*series
print('pi=', pi)

pi= 3.1415926535714034


### 98. write a function to check if the number is harshad or not A Harshad number is an integer that is divisible by the sum of its digits (for example, 21 is divisible by 2+1=3 and so is a Harshad number).

In [13]:
num = input()

l=[int(num[x]) for x in range(len(num))]

print(l)

if(int(num)%sum(l)==0):
    print("Harshed")
else:
    print("Not Harshed")

45
[4, 5]
Harshed


### 99. write a function select_word(): to get a random word from a list of words use module random and call random.randint() to chose random

In [15]:
import random 
 
word_list = ["I", "am", "shakiba"] 
random_word = random.choice(word_list) 
print(random_word)

shakiba


### 100. write a function blank(word): where it should print _ after first letter to the range of length of word i.e apple= a _ _ _ _

In [24]:
def blanck_word(str):
    L=[ i  for i in str]
    for i in range(1,len(L)):
        L[i]="-"
    return ''.join(L)
print(blanck_word("shakiba"))    

s------


### 101.compete the code below

In [ ]:
write a code in your code section
def clue(str):
    L=[ i  for i in str]
    for i in range(1,len(L)):
        L[i]="-"
    return ''.join(L)




def hang_man(word,clue,letter,try=True):
    # create a variable "try" and set it to True
    try=len(word)
    #--------------------------------
    # loop through the length of the word
    for i in range(len(word)):
        if i==letter:
            clue(i+letter+clue)
            try=len(word)-1
           
            
        # check condition if word is equal to letter
        #the set clue= clue from o to current index of loop + letter + clue from current index +1 to last
        # your code
        #set try to false
        # your code
    #---------------------------------------------------
    # check condition if try is true then decrease the try_left by 1
    # your code
        print("wrong try", try_left)
    print("you got so far",clue)

    # check if word is equal to clue:
    #your code
        print("you win")
    # check is try_left is 0:
    # your code
        print("you lost")
    else:
        # ask user to input next letter 
        #next_letter="your code"
        # call the recursive function of itself

word=# call a function select word
clue=# call a function balnk
 call a function hang_man() where set letter to word[0] and try_left to=5

### 102. write a map function which calculate the list multiple of 5: eg: x == [ 2, 3, 4, 5, 6] y == [10, 15, 20, 25, 30]

In [25]:
my_list = [ 2, 3, 4, 5, 6]
print(list(map(lambda x:x*5, my_list)))

[10, 15, 20, 25, 30]


### 103. write a map function which multiply the odd values by 5 and add them to the list

In [31]:
my_list = [ 2, 3, 4, 5, 6]
L1=[i for i in my_list if i%2!=0]
L2=(list(map(lambda x:x*5,L1)))
L2.extend(my_list)
print(L2)


[15, 25, 2, 3, 4, 5, 6]


### 104. write a map fu
nction to get: x=[2,3,4] y=[4,5] ans: z=[[6,7],[7,8],[8,9]]

In [64]:
x=[2,3,4]
y=[4,5]
A=[]
for i in y:
    L2=(list((map(lambda x:x+i,x))))
    A.append(L2)
new_lst = [list(x) for x in zip(A[0],A[1])]
print(new_lst)

    
    
    
    
   



[[6, 7], [7, 8], [8, 9]]


### 105. write a function to convert a z list to 1d list : use reduce

In [66]:
from functools import reduce 

reduce(lambda x,y :x+y ,[[1,2,3],[1,2],[1,4,5,6,7]])


[1, 2, 3, 1, 2, 1, 4, 5, 6, 7]

### 107.write a function using a type annotations which take a two vector a and b which calculate the vector sum eg: [1,2,3]+[4,5,6]=[5,7,9] 

In [67]:
a = [1,2,3]
b = [4,5,6]
print(list(map(lambda x,y: x+y, a, b)))

[5, 7, 9]


### 108. write a function which using a type annotation to calculate te dot product of two vector
eg: [1,2,3]+[4,5,6]=32

In [4]:
def multivector(a,b):
     return(sum(list(map(lambda x,y: x*y, a, b))))
    


print(multivector([1,2,3],[4,5,6]))       
    
    

32


### 109. write a function to calculate the sum of vector which take a list of vector using type annotation eg:[1,2],[3,4],[5,6]=[9,12]

In [8]:
def multivector(a,b,c):
    return (list(map(lambda x,y,z: x+y+z, a, b, c)))


print(multivector([1,2],[3,4],[5,6]))        
    

[9, 12]


### 110. write a function to get the shape of a matrix also use type annotation: eg:[[1,2],[2,3]]=(2,2)

In [9]:
def shape(a):
    for i in a:
        b=len(i)
    return(len(a),b)

print(shape([[1,2],[2,3]]))

(2, 2)


### 111. write a functions to create a matrix and used function to crete a 3*3 identity matrix : hint:use a Callable from typing

In [12]:
import numpy as np
def Matrix():
    print("Enter the number in a single line separated by space:")
    val = list(map(int, input().split()))
    matrix = np.array(val).reshape(a,b)
    return matrix

a = int(input("Enter the number of rows:"))
b = int(input("Enter the number of columns:"))
print(Matrix())

Enter the number of rows:3
Enter the number of columns:3
Enter the number in a single line separated by space:
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 112. follow the link https://www.willamette.edu/~gorr/classes/cs449/reber.html and try to generate a embedded reber grammar as shown in fig 2. HINT: -first create a list of list of tuple of reber_ grammar

the node and edges are:

B=1,T=2, P=3, S=2,X=4,T=3,V=5,X=3,S=6,P=4,V=6,E=None

create a list of tuple of (edge,Node)

eg:[[("B",1)], [(),()]]

after that crete a list as shown in graph in figure 2

In [ ]:
def generate_reber_string(grammar):
    s=0
    optput=[]
    # loop untill s in not None:
        p,s=grammar[s][np.random.randint(len(grammar[s]))]
        # if instane is still list:
            # call the function again
        #append the called funcion output to output
    #return the join output

In [ ]:
import random
import numpy as np
def grammer():
    List=[]
    k1=1
    nod=[1,2,3,4,5,6]
    List2=[("T",(1,2)),("P",(1,3)),("S",(2,2)),("X",(2,4)),("T",(3,3)),("V",(3,5)),("X",(4,3)),("S",(4,6)),("P",(5,4)),("V",(5,6)),("E",(6,None))]
    while k1!=6:
        k2=np.random.randint(1,len(nod)+1)
        print(k2)
        for j in List2:
            if (k1,k2) in j:
                List.append(j[0])
                k1=k2
    return List
    


#for i in grammer():
    #print(i) 
print(grammer())

### 113. write a function to generate a password :
password should have a number,special_char,alphabet(both capital and small)
allow user to input the length of password

In [3]:
import re

def password(a):
    reg="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{8,18}$"
    match_re = re.compile(reg)
    res = re.search(match_re, a)
    if res:
        print("Valid Password")
    else:
        print("Invalid Password")




a=input()
length_pass=input()
password(a)

asd@Asd1
8
Valid Password


### 114. write a function to get the integers satisfying a2+b2=c2 called Pythagorean numbers.
the function take a input from a user with a maximal number: eg: if user give: 5 it should print (3,4) similarly:10 3 ,4 6,8

In [6]:
def pythagorean(c):
    for b in range(1,c):
        for a in range(1,b):
            if ((a**2 + b**2) == c**2):
                print((a, b))    
pythagorean(5)

(3, 4)


### 115. write a program to guess a random number between range 1 to n



In [8]:
import random
guessesTaken = 0
print("I am guessing a number between 1 to 30, what is that?")
number = random.randint(1, 30)
while True:
    user_num = int(input())
    if user_num == 0:
        break
    if user_num < number:
        print('Your guess is too low.')
    if user_num > number:
        print('Your guess is too high.')
    if user_num == number:
        print('Perfect')
        break

I am guessing a number between 1 to 30, what is that?
12
Your guess is too high.
7
Your guess is too low.
10
Your guess is too low.
11
Perfect


### 116. Write a function which takes a text and encrypts it with a Caesar cipher as well as decrypt.(https://en.wikipedia.org/wiki/Caesar_cipher) .

In [ ]:
input:"hello",
output: encrypt:EBIIL
decyprt: HELLO

In [25]:
alphabet=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
L1=list(enumerate(alphabet))
L3=[]
def encrypts(str):
    for i in str:
        for j in range(len(L1)):
            if i==L1[j][1]:
                k=j-3
                L3.append(L1[k][1])
    return "".join(L3)
    
str=input(" ")
print(encrypts(str))
                
                
                
                
    


 SHAKIBA
PEXHFYX


### 117.write a function which take a text and dictionary to decrypt or encrypt the text with a permutated alphabet hint:

In [5]:
import random
import string
key=input("please enter your key: ")
key=''.join([j for i,j in enumerate(key) if j not in key[:i]])
letters = "abcdefghijklmnopqrstuvwxyz"
for j in key:
    for i in letters:
        if j==i:
            letters=letters.replace(i,"")
newalphabet=key+letters
L1=list(enumerate(newalphabet))
A=[]
letters1 = "abcdefghijklmnopqrstuvwxyz"
for i in letters1:
    A.append(i)
L2=list(enumerate(A))

choose=input("Would you like to encrypt or decrypt? ")
str=input("please enter your message ")
if choose=="encrypt":
    L3=[]
    def encrypt(str):
        for i in str:
            if i ==" ":
                L3.append(" ")
            else:
                for j in range(len(L2)):
                    if i==L2[j][1]:
                        k=L2[j][0]
                        L3.append(L1[k][1])
                
                    
                
        
        return "".join(L3)
    print(encrypts(str))
elif choose=="decrypt":
    L4=[]
    def decrypt(str):
        for i in str:
            if i ==" ":
                L4.append(" ")
            else:
                for j in range(len(L1)):
                    if i==L1[j][1]:
                        k=L1[j][0]
                        L4.append(L2[k][1])
                    
        return "".join(L4)
    print(decrypt(str))

else:
        print("You need to enter in a valid answer. Please try again. ") 


please enter your key: shakiba
Would you like to encrypt or decrypt? decrypt
please enter your message hi tehran
be tibsco


### 120.write a recursive function for f(n) = 7 * n, i.e. the multiples of 7 

In [26]:
def mul_table(N, i):
     
   
    if (i>10):
        return
    else:
        print(N,"*",i,"=",N * i)
        return mul_table(N, i + 1)

mul_table(7, 1)

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70


### 121. Write a function which implements the Pascal's triangle use recursion

### 133. write a decorator to count the number of times a function has beeen called . eg define a add function and loop it for 10 time and check

In [7]:
def outer_add(f):
    global k
    k=0
    def inner_add(t):
        global k
        k+=1
        return f(t)
    return inner_add

@outer_add
def add(a):
    return a+2
for i in range(10):
    print(add(i)) 
k


2
3
4
5
6
7
8
9
10
11


10

In [6]:
l="shakina"
print(l.split(" "))

['shakina']
